Benny branch
LuckyFlower2995/Foodingo pull request #4
Opened 2023-10-06 23:34 UTC by lanbenny6

Added navigation function for level map and a get started message when you press the icon.

2023-10-07 00:03 UTC, LuckyFlower2995 approved these changes
Looks good. Thanks Benny

2023-10-07 00:07 UTC, Ela01 reviewed
Nice job!

2023-10-07 00:09 UTC, Ela01 requested changes
:)

2023-10-08 02:44 UTC, Ela01 approved these changes

2023-10-08 02:44 UTC, merged